export type Lang = "en" | "hi";

const strings = {
  en: {
    appName: "UniJobs",
    tagline: "Find work. Hire workers.",
    getStarted: "Get Started",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिन्दी",
    selectRole: "Who are you?",
    worker: "Worker",
    workerDesc: "Looking for a job",
    employer: "Employer",
    employerDesc: "Looking to hire",
    admin: "Admin",
    adminDesc: "Manage platform",
    register: "Register",
    loginByPhone: "Login by Phone",
    loginByEmail: "Login by Email",
    workerRegistration: "Worker Registration",
    companyRegistration: "Company Registration",
    name: "Full Name",
    fatherName: "Father's Name",
    phone: "Phone Number",
    aadhaar: "Aadhaar Number",
    uan: "UAN Number",
    address: "Address",
    city: "City",
    education: "Education",
    experience: "Experience",
    category: "Job Category",
    companyName: "Company Name",
    ownerName: "Owner Name",
    email: "Email",
    enterPhone: "Enter registered phone",
    enterEmail: "Enter registered email",
    find: "Find Account",
    back: "Back",
    save: "Save Changes",
    cancel: "Cancel",
    edit: "Edit Profile",
    logout: "Logout",
    loading: "Loading…",
    myProfile: "My Profile",
    requirements: "Job Requirements",
    noRequirements: "No requirements posted yet",
    dashboard: "Dashboard",
    pendingMsg: "Your company is pending admin approval.",
    rejectedMsg: "Your company registration was rejected.",
    searchWorkers: "Search Workers",
    filterCategory: "Category",
    filterCity: "City (optional)",
    allCategories: "All Categories",
    search: "Search",
    noWorkers: "No workers found",
    postRequirement: "Post Requirement",
    reqTitle: "Title",
    reqDescription: "Description (optional)",
    reqVacancies: "Vacancies",
    reqCity: "City",
    post: "Post",
    myRequirements: "My Requirements",
    companies: "Companies",
    allWorkers: "All Workers",
    approve: "Approve",
    reject: "Reject",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    adminPanel: "Admin Panel",
    adminLogin: "Admin Login",
    adminPassword: "Admin Password",
    login: "Login",
    wrongPassword: "Wrong password",
    error: "Something went wrong. Try again.",
    alreadyExists: "Already registered with this phone / email",
    status: "Status",
    vacancies: "vacancies",
  },
  hi: {
    appName: "यूनीजॉब्स",
    tagline: "काम खोजें। कर्मचारी ढूंढें।",
    getStarted: "शुरू करें",
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिन्दी",
    selectRole: "आप कौन हैं?",
    worker: "कर्मचारी",
    workerDesc: "नौकरी की तलाश में",
    employer: "नियोक्ता",
    employerDesc: "भर्ती करना चाहते हैं",
    admin: "एडमिन",
    adminDesc: "प्लेटफॉर्म प्रबंधन",
    register: "पंजीकरण",
    loginByPhone: "फोन से लॉगिन",
    loginByEmail: "ईमेल से लॉगिन",
    workerRegistration: "कर्मचारी पंजीकरण",
    companyRegistration: "कंपनी पंजीकरण",
    name: "पूरा नाम",
    fatherName: "पिता का नाम",
    phone: "फोन नंबर",
    aadhaar: "आधार नंबर",
    uan: "यूएएन नंबर",
    address: "पता",
    city: "शहर",
    education: "शिक्षा",
    experience: "अनुभव",
    category: "नौकरी श्रेणी",
    companyName: "कंपनी का नाम",
    ownerName: "मालिक का नाम",
    email: "ईमेल",
    enterPhone: "पंजीकृत फोन दर्ज करें",
    enterEmail: "पंजीकृत ईमेल दर्ज करें",
    find: "खाता खोजें",
    back: "वापस",
    save: "बदलाव सहेजें",
    cancel: "रद्द करें",
    edit: "प्रोफ़ाइल संपादित करें",
    logout: "लॉगआउट",
    loading: "लोड हो रहा है…",
    myProfile: "मेरी प्रोफ़ाइल",
    requirements: "नौकरी की आवश्यकताएं",
    noRequirements: "अभी तक कोई आवश्यकता नहीं",
    dashboard: "डैशबोर्ड",
    pendingMsg: "आपकी कंपनी एडमिन अनुमोदन के लिए प्रतीक्षित है।",
    rejectedMsg: "आपका पंजीकरण अस्वीकार कर दिया गया।",
    searchWorkers: "कर्मचारी खोजें",
    filterCategory: "श्रेणी",
    filterCity: "शहर (वैकल्पिक)",
    allCategories: "सभी श्रेणियां",
    search: "खोजें",
    noWorkers: "कोई कर्मचारी नहीं मिला",
    postRequirement: "आवश्यकता पोस्ट करें",
    reqTitle: "शीर्षक",
    reqDescription: "विवरण (वैकल्पिक)",
    reqVacancies: "रिक्तियां",
    reqCity: "शहर",
    post: "पोस्ट करें",
    myRequirements: "मेरी आवश्यकताएं",
    companies: "कंपनियां",
    allWorkers: "सभी कर्मचारी",
    approve: "अनुमोदित",
    reject: "अस्वीकार",
    approved: "अनुमोदित",
    rejected: "अस्वीकृत",
    pending: "प्रतीक्षित",
    adminPanel: "एडमिन पैनल",
    adminLogin: "एडमिन लॉगिन",
    adminPassword: "एडमिन पासवर्ड",
    login: "लॉगिन",
    wrongPassword: "गलत पासवर्ड",
    error: "कुछ गलत हुआ। पुनः प्रयास करें।",
    alreadyExists: "यह फोन / ईमेल पहले से पंजीकृत है",
    status: "स्थिति",
    vacancies: "रिक्तियां",
  },
};

export const CATEGORIES = [
  "Picker", "Scanner", "Delivery", "Packing",
  "Warehouse Helper", "Loader", "Tagging",
];

export const EDUCATION = [
  "Below 10th", "10th Pass", "12th Pass", "Graduate", "Post Graduate",
];

export default strings;
